name: flutter_chat_demo
description: This is the demo for chat app by Flutter
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.2.0
  fluttertoast: ^8.0.7
  image_picker: ^0.8.0
  shared_preferences: ^2.0.6
  firebase_storage: ^8.1.0
  cached_network_image: ^3.0.0
  intl: ^0.17.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^6.0.0
  photo_view: ^0.11.1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/img_not_available.jpeg
    - assets/images/mimi1.gif
    - assets/images/mimi2.gif
    - assets/images/mimi3.gif
    - assets/images/mimi4.gif
    - assets/images/mimi5.gif
    - assets/images/mimi6.gif
    - assets/images/mimi7.gif
    - assets/images/mimi8.gif
    - assets/images/mimi9.gif
    - assets/images/logo.png
